[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.25"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@prb/math/=lib/prb-math/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
